// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package model

// Defines values for SortBy.
const (
	SortByCreated SortBy = "created"

	SortById SortBy = "id"

	SortByModified SortBy = "modified"

	SortByName SortBy = "name"

	SortByRandom SortBy = "random"

	SortByRating SortBy = "rating"
)

// SortBy defines model for SortBy.
type SortBy string

