openapi: 3.0.1
info:
  version: 1.0.0
  title: Fankey API
  description: Fankey API
tags:
  - name: pet
  - name: user
paths:
  /pets:
    post:
      summary: Returns all pets
      description: description
      operationId: PostPet
      parameters: []
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './payload.yaml#/components/schemas/PostPetResponse'
      tags:
        - pet
      requestBody:
        content:
          application/json:
            schema:
              $ref: './payload.yaml#/components/schemas/PostPetRequest'
    get:
      summary: List Pets
      operationId: ListPets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './payload.yaml#/components/schemas/ListPetResponse'
      parameters:
        - schema:
            $ref: './param.yaml#/components/schemas/SortBy'
          in: query
          name: sortBy
      tags:
        - pet
      description: description
  /users:
    post:
      summary: PostUser
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './payload.yaml#/components/schemas/PostUserResponse'
      operationId: PostUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: './payload.yaml#/components/schemas/PostUserRequest'
      description: description
components:
  schemas: {}
