openapi: 3.0.1
info:
  version: 1.0.0
  title: Fankey API
  description: Fankey API
tags:
  - name: pet
  - name: user
paths:
  /pets:
    post:
      summary: Returns all pets
      description: description
      operationId: FindPets
      parameters: []
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostPetResponse'
      tags:
        - pet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostPetRequest'
    get:
      summary: List Pets
      operationId: ListPets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPetResponse'
      parameters:
        - schema:
            $ref: ./param.yaml#/components/schemas/SortBy
          in: query
          name: sortBy
      tags:
        - pet
      description: description
  /users:
    post:
      summary: PostUser
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostUserResponse'
      operationId: PostUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUserRequest'
      description: description
components:
  schemas:
    PostPetResponse:
      type: object
      x-tags:
        - pet
      title: ''
      properties:
        id:
          type: string
    PostPetRequest:
      title: PostPetRequest
      type: object
      x-tags:
        - pet
      properties:
        id:
          type: string
    PostUserRequest:
      title: PostUserRequest
      type: object
      properties:
        id:
          type: string
      x-tags:
        - user
    PostUserResponse:
      title: PostUserResponse
      type: object
      properties:
        id:
          type: string
      x-tags:
        - user
    ListPetResponse:
      title: ListPetResponse
      type: object
      properties:
        id:
          type: string
