openapi: 3.0.1
info:
  version: 1.0.0
  title: Fankey API
  description: Fankey API
tags:
  - name: pet
paths:
  /pets:
    post:
      summary: Returns all pets
      description: ''
      operationId: FindPets
      parameters: []
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FindPetResponse'
      tags:
        - pet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FindPetRequest'
    get:
      summary: ''
      operationId: GetPets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindPetResponse'
      parameters:
        - schema:
            $ref: ./params.yaml#/components/schemas/sortBy
          in: query
          name: sortBy
      tags:
        - pet
      description: ''
components:
  schemas:
    FindPetResponse:
      type: object
      properties:
        id:
          $ref: ./params.yaml#/components/schemas/PetId
        name:
          type: string
    FindPetRequest:
      title: FindPetRequest
      type: object
      x-tags:
        - pets
      properties:
        id:
          $ref: ./params.yaml#/components/schemas/PetId
        sortBy:
          $ref: ./params.yaml#/components/schemas/sortBy
