openapi: 3.0.1
info:
  title: fankey-api
  version: 1.0.0
paths: {}
components:
  schemas:
    sortBy:
      type: string
      enum:
        - name
        - id
        - rating
        - created
        - modified
        - random
    PetId:
      title: PetId
      type: string
