openapi: 3.0.1
info:
  title: fankey-api
  version: 1.0.0
paths: {}
components:
  schemas:
    SortBy:
      type: string
      enum:
        - name
        - id
        - rating
        - created
        - modified
        - random
      title: SortBy
