openapi: 3.0.1
info:
  title: fankey-api
  version: 1.0.0
paths: {}
components:
  schemas:
    PostPetResponse:
      type: object
      x-tags:
        - pet
      title: ''
      properties:
        id:
          type: string
    PostPetRequest:
      title: PostPetRequest
      type: object
      x-tags:
        - pet
      properties:
        id:
          type: string
    PostUserRequest:
      title: PostUserRequest
      type: object
      properties:
        id:
          type: string
      x-tags:
        - user
    PostUserResponse:
      title: PostUserResponse
      type: object
      properties:
        id:
          type: string
      x-tags:
        - user
    ListPetResponse:
      title: ListPetResponse
      type: object
      properties:
        id:
          type: string
